# Generated by Django 4.2 on 2025-08-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_remove_patientmodules_module_and_more'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodules',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
            preserve_default=False,
        ),
    ]
