# Generated by Django 4.2 on 2025-07-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medicationnotificationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationNotificationSettings',
        ),
    ]
