# Generated by Django 4.2 on 2025-09-02 07:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_delete_medicationnotificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicine',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='frequency',
            field=models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='once', max_length=30),
        ),
        migrations.AlterField(
            model_name='patientmedicine',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
