# Generated by Django 4.2 on 2026-01-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_clinic_manager_remove_user_is_doctor_and_more'),
        ('clinics', '0004_remove_patientmodules_module_and_more'),
        ('medications', '0005_alter_patientmedicine_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationsBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=255)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('medicines', models.ManyToManyField(related_name='bundled_medicines', to='medications.medicines')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicationsBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication_bundles', to='medications.medicationsbundle')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medication_bundles', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication_bundles', to='users.patient')),
            ],
        ),
    ]
