# Generated by Django 4.2 on 2025-08-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0003_clinicmodules_is_active_modules_module_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='questionnaire name')),
                ('type', models.CharField(choices=[('measurement', 'measurement'), ('questionnaire', 'questionnaire')], default='measurement', max_length=20, verbose_name='questionnaire type')),
                ('is_module', models.BooleanField(default=False, verbose_name='is module?')),
                ('language', models.CharField(choices=[('he', 'Hebrew'), ('en', 'English')], default='en', max_length=5, verbose_name='language')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public?')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible?')),
                ('order_important', models.BooleanField(default=False, verbose_name='order important')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('short text', 'text'), ('image', 'image'), ('button', 'button'), ('file', 'file'), ('toggle', 'toggle'), ('slider', 'slider'), ('scale', 'scale'), ('paragraph', 'paragraph'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('dropdown', 'dropdown'), ('audio', 'audio'), ('calendar', 'calendar')], default='text', max_length=20, verbose_name='object type')),
                ('object_name', models.CharField(max_length=1000, verbose_name='object name')),
                ('object_description', models.CharField(blank=True, max_length=1000, verbose_name='object description')),
                ('has_options', models.BooleanField(default=False, verbose_name='has options')),
                ('options', models.CharField(blank=True, max_length=1000, verbose_name='options')),
                ('random_selection_of_options', models.BooleanField(default=False, verbose_name='random selection of options')),
                ('object_screen', models.IntegerField(verbose_name='object screen')),
                ('object_order', models.IntegerField(verbose_name='object order')),
                ('expected_answer', models.CharField(blank=True, max_length=1000, verbose_name='expected answer')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_objects', to='questionnaires.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='clinics.clinic')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_questionnaires', to='questionnaires.questionnaire')),
            ],
        ),
    ]
