# Generated by Django 4.2 on 2025-09-02 07:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientactivity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='patientactivity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='patientactivity',
            name='frequency',
            field=models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='once', max_length=30),
        ),
        migrations.AddField(
            model_name='patientactivity',
            name='frequency_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='patientactivity',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
