# Generated by Django 4.2 on 2026-01-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_remove_patientmodules_module_and_more'),
        ('users', '0006_remove_user_is_clinic_manager_remove_user_is_doctor_and_more'),
        ('activities', '0003_remove_patientactivity_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=255)),
                ('activities', models.ManyToManyField(related_name='bundled_activities', to='activities.activity')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='PatientActivitiesBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_activity_bundles', to='activities.activitiesbundle')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_activity_bundles', to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_activity_bundles', to='users.patient')),
            ],
        ),
    ]
