# Generated by Django 4.2 on 2025-07-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_reasearch_patient',
            new_name='is_research_patient',
        ),
    ]
