# Generated by Django 4.2 on 2025-07-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0002_rename_is_reasearch_patient_user_is_research_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
        ),
    ]
