# Generated by Django 4.2 on 2025-08-04 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patientdoctor_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, verbose_name='user id')),
                ('msg_type', models.CharField(blank=True, choices=[('EMAIL', 'email'), ('SMS', 'SMS/Text Message')], max_length=10, verbose_name='message type')),
                ('sender', models.CharField(max_length=255, verbose_name='sender string')),
                ('destinatary', models.CharField(max_length=255, verbose_name='destinatary string')),
                ('sent_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('SUCCESS', 'message sent'), ('FAIL', 'message not sent')], default='FAIL', max_length=10, verbose_name='message status')),
                ('registered', models.BooleanField(blank=True, default=False, verbose_name='registered')),
            ],
        ),
    ]
