# Generated by Django 4.2 on 2025-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sentmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CLINIC_MANAGER', 'Clinic Manager'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('RESEARCH_PATIENT', 'Research Patient')], max_length=30),
        ),
    ]
