# Generated by Django 4.2 on 2025-08-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_clinic_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_research_patient',
        ),
    ]
