# Generated by Django 4.2 on 2026-01-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_clinic_manager_remove_user_is_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sentMessages',
        ),
    ]
