# Generated by Django 4.2 on 2025-07-30 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0003_patientdoctor_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('medication', 'Medication'), ('activity', 'Activity'), ('questionnaire', 'Questionnaire')], max_length=30, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], max_length=30, null=True)),
                ('frequency_data', models.JSONField(blank=True, default=list, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
