# Generated by Django 4.2 on 2025-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinic_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
