# Generated by Django 4.2 on 2025-08-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_clinic_manager_remove_user_is_doctor_and_more'),
        ('clinics', '0002_clinic_clinic_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmodules',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='module_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.modules')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
