# Generated by Django 4.2 on 2025-08-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinicmodules_is_active_modules_module_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmodules',
            name='module',
        ),
        migrations.RemoveField(
            model_name='patientmodules',
            name='patient',
        ),
        migrations.DeleteModel(
            name='ClinicModules',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='PatientModules',
        ),
    ]
